export enum CollectionNames {
  EMPLOYEE = "employees",
  ROLE = "roles",
  USER = "users",
  NEWS = "news",
  CATEGORIES = "categories",
  SUBJECTS = "subjects",
  SECTIONS = "sections",
  TOPICS = "topics",
  TEST = "tests",
  QUESTION = "testquestions",
  ANSWER = "answers",
  REGIONS = "regions",
  QUIZ = "quizes",
  CLASS = "classes",
}
